# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    mp.form.registration:
        class: MpBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: mp_user_registration }
